### ISSUE TITLE
Minor edit needed to Index.html

### ISSUE THREAD

**Issue by tudza** [alikifah/MagicClock#3]
Thank you for posting this. I have two Javascript clocks I've made, but this will make the job much easier.

I downloaded your code and loaded Index.html. One clock face was black.

I just needed to capitalize the hour, minute, and second hand file names and got clock theme 2 to display.

**Comment by alikifah** [comment]
I've edited the index.html file.
Thank you

**Comment by tudza** [comment]
I see all four sample clocks.
