### ISSUE TITLE
Window for date display

### ISSUE THREAD

**Issue by tudza** [alikifah/MagicClock#5]
This has me stumped at the moment. 

I added a window for the date in my clock face art.  I have managed to get the date to show in the window when displayed on my desktop browser but the face moves over the position of the date on another computer and on my phone.

The problem is probably that I'm using absolute positioning. Also, the date is generated outside your very nice javascript and I can not figure out where to put my bit in there were it belongs to show the date in relation to the clock face art.

https://tudza.org/MagicClockRolex_Smooth_Hands/Rolex.html

**Comment by alikifah** [comment]
Hello,
I've updated the js and the index file. take a look at the new changes!
enjoy!

**Comment by tudza** [comment]
Thank you. I will have a look.

I'm sure your solution will beat mine. I managed to get something passable by putting the whole thing in an iframe which did fix the date to the same place in all browsers I checked and when I changed the browsers from full screen to a smaller window, but I'm guessing this is not the correct way to do it.

**Comment by alikifah** [comment]
With the changes I've made to the js file you can now add multiple captions directly to the canvas at a specific coordinate with the new function "addCaption" of the MagicClock class.
the changes in the index file should make every thing clear.

**Comment by tudza** [comment]
Took me a while to figure out the x and y values for the date window, but it was simple enough. As expected, the correct way to place the date looks much cleaner than what I cobbled together.

( Finally occurred to me to change the date to white on my black clock face to help get the x,y values right. )

This is what I've posted just now with the date and changes to hour, minute, and second calculations.

https://tudza.org/Rolex_Date_Window/Index.html

Thanks for the update.

Final question. I see that "new Date().getDate()" in Index.html and I see within the javascript file where the hour, minute, and second values get updated, but I can't tell how the day gets updated. That is, with the code as it is, will the date change at midnight?

**Comment by alikifah** [comment]
glad to know, that it worked fine for you.
As for your question, the value of "new Date().getDate()" represents the actual date at the moment the function gets called.
That means, that once set(on loading the page inside the function "addCaption"), the date value will not be updated automatically without refreshing the page. 
If you need a real time updating of the date value without refreshing the page, a new logic should be implemented(inside the main canvas render loop), but that would not be so hard to do.
If you need any help or more modifications feel free to ask.

**Comment by tudza** [comment]
My solution when I put in the date function myself was to just put a meta tag in to refresh the page every five minutes or so. That is certainly sufficient for my uses.

Thanks for the answers.
